blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name="Blog"),
    path('categoria/<int:categoria_id>/', views.categoria, name="Categoria"),
]

carro/urls.py
from django.urls import path
from . import views

#Este nombre se coloca por si tenemos otras rutas iguales que no colisionen entre si, si no que añadiendo el namespace delante listo {% url 'carro:agregar' producto.id %}
app_name = "carro"

urlpatterns = [
    # path('', views.servicio, name="Carro"),
    path("agregar/<int:producto_id>/", views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>/', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>/', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_carro, name="limpiar"),
]

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoWebApp.urls')),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('carro/', include('carro.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('pedidos/', include('pedidos.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT )

tienda/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.tienda, name="Tienda"),  
]

carro/models.py
from django.db import models

# Create your models here.

tienda/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.


class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=100)
    contenido = models.CharField(max_length=50)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)

    class Meta :
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"
    
    def __str__(self) :
        return self.nombre


class Producto(models.Model):
    nombre=models.CharField(max_length=100)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda" ,null = True, blank = True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)


    class Meta :
        verbose_name = "producto"
        verbose_name_plural = "productos"
    
    def __str__(self) :
        return self.nombre

carro/views.py
from tkinter import OUTSIDE
from django.shortcuts import render,redirect
from .carro import Carro
from tienda.models import Producto

# Create your views here.


def servicio(request):
    return render(request,"carro/carro.html")



def agregar_producto (request , producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.agregar(producto)
    return redirect('Tienda')




def eliminar_producto (request , producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.eliminar(producto)
    return redirect('Tienda')


def restar_producto (request , producto_id):
    carro = Carro(request)
    producto = Producto.objects.get(id = producto_id)
    carro.restar_producto(producto)
    return redirect('Tienda')

def limpiar_carro (request):
    carro = Carro(request)
    carro.limpiar_carro()
    return redirect('Tienda')

tienda/views.py
from django.shortcuts import render
from .models import CategoriaProd, Producto

# Create your views here.



def tienda(request):

    productos = Producto.objects.all()

    return render(request,"tienda/tienda.html", {'productos' : productos})

tienda/templates/carro/widget.html
<table class="table tabler-bordered" style="color: white;">

    <thead>
        <tr>
            <th colspan="3" class="text-center"> Carro compras</th>
        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>
        </tr>

    </thead>

    <tbody>

        {% if request.session.carro.items %}
        {% for key,value in request.session.carro.items %}
        {# aquí mostramos los productos que tenemos en el carro #}
        <tr class="text-center">
            <th>{{value.nombre}}</th>
            <th>{{value.cantidad}}</th>
            <th>
                <a href="{% url 'carro:agregar' value.producto_id %}" class="btn  btn-sm btn-success"> +</a>
                <a href="{% url 'carro:restar' value.producto_id %}" class="btn  btn-sm btn-success"> -</a>
                <br>
                {{value.precio}}

            </th>
        </tr>
        {% endfor %}
        {% else %}
        <th>
        <td colspan="3">
            <div class="alert alert-danger text-center">
                SIN PRODUCTOS
            </div>
        </td>
        </th>

        {% endif %}

        

    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">
                <p style="color: white;"> total : {{importe_total_carro}}</p>
            </td>
        </tr>

        {% if request.session.carro.items %}
        <tr>
            <td colspan="3" style="text-align:center;">
                <a href="{% url 'Pedidos' %}" class="btn btn-success">Realizar pedido</a>
            </td>
        </tr>
        {% endif %}

    </tfoot>
    

</table>